theme: jekyll-theme-cayman
language: spanish
favicon: assets/logo.png
uistring:
    title: Ayphu mi primera p치gina # title to appear in nav bar and page meta
    description: Creaci칩n de una p치gina est치tica utilizando Github Pages con archivo .md # Displays as site description meta tag for site
